### ISSUE TITLE
thingsboard-rule-config-ui-ngx/projects/rulenode-core-config/tsconfig.lib.json config error

### ISSUE THREAD

**Issue by kywvane** [thingsboard/thingsboard-rule-config-ui-ngx#11]
should use lib es2019
if not and keep use es2018 cause error in next code：
let resModules = (res as Type<any>[][]).flat();

**Comment by kywvane** [comment]
error code file
node_modules\thingsboard\src\app\modules\home\components\widget\widget-component.service.ts

this cause by commit UI: External angular modules for widget development , 20.7.15

**Comment by vvlladd28** [comment]
Hi @kywvane,
Thank you, we have already corrected this.
