### ISSUE TITLE
yarn run build error

### ISSUE THREAD

**Issue by freebooterish** [thingsboard/thingsboard-rule-config-ui-ngx#57]
Hi,sir, the newest commit report error:
✔ Compiling with Angular sources in Ivy partial compilation mode.
✖ Bundling to FESM2015
line.trim(...).split(...)[0].replaceAll is not a function
error Command failed with exit code 1.

**Comment by vvlladd28** [comment]
Hi @freebooterish,
For the build latest version UI rule node, you need to use Node.JS 16.x (LTS)

**Comment by freebooterish** [comment]
> Hi @freebooterish, For the build latest version UI rule node, you need to use Node.JS 16.x (LTS)

Thank you!
